-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoCUR78OOWNFSREN6
jSob6fK21nwcHts0BGaDkAZJmt6gCgYIKoZIzj0DAQehRANCAATIEA9bkmwcYLNr
le5Z+Tnsn1hPSgxZAhgVWaTrRfXdJoBmvGTDcCEbB3QBpeYtmGDlUXJ8zmvq28uD
e4VjQq6k
-----END PRIVATE KEY-----